name: "CI"

on: [pull_request]

jobs:
  build:
    name: Check format, lint, build, and test

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2

      - name: "Use latest Node LTS"
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: "Install dependencies"
        run: yarn install

      - name: "Check format"
        run: yarn format:check

      - name: "Lint"
        run: yarn lint

      - name: "Build"
        run: yarn build
